### ISSUE TITLE
Error: Invalid hook call - when running any command

### ISSUE THREAD

**Issue by m4tty-d** [fauna-labs/fauna-schema-migrate#106] opened 2021-11-08 15:55 UTC
I'm getting the following error, for each command:

![image](https://user-images.githubusercontent.com/6316925/140774148-d7c5b039-c197-4eea-a980-6f61a1ddc28b.png)

I tried both by installing the package and using npx, same result either way.

**Comment by rts-rob** [comment] 2021-11-08 16:01
Hi @m4tty-d - thanks for reporting.

I'm keying in on one line here:

> You might have more than one copy of React in the same app

Are you building a React app with a different version of React? Do you get these errors if you create a "clean" repo in an empty directory as follows?

* `npm init --yes`
* `npm install --save-dev @fauna-labs/fauna-schema-migrate`
* `npx fauna-schema-migrate run`

**Comment by m4tty-d** [comment] 2021-11-08 17:04
No, I don't have React as a dependency in my project, so I don't think that it's related to that.

I tried the tool in the [Workers template](https://github.com/fauna-labs/fauna-workers) repo and I had no issues there.
So I did some digging and found that the only difference between that repo and mine is the package-lock.json.
It suggests that it is using an older npm version (probably version 6 or older based on lockfileVersion 1).

So using the latest npm version (8.1.3) the issue should be reproducible.

**Comment by rts-rob** [comment] 2021-11-08 17:25
That does it - thanks!

Reproduced with:
* Node.js v16.13.0 and npm v8.1.0/8.1.3
* Node.js v14.17.6 and npm v8.1.3

So it looks like npm is the culprit here.

For context, we had been holding everything back to npm v6 and Node v14 as it was the most recent LTS. Now that Node v16 is LTS we'll need to bring this up to date.

Workaround is to use Node v14 **with npm v6**

**Comment by rts-rob** [comment] 2021-11-08 17:36
Appears to be fixed in https://github.com/vsashyn/ink-syntax-highlight/pull/3 by our very own @ptpaterson.

Since that has sat unmerged since February I'm going to temporarily fork it and update it. Ultimately we're going to need to remove ink as it's causing all of these problems (including needing React in the first place).

**Comment by rts-rob** [comment] 2021-11-08 18:01
Oh, one more workaround - you can use the `--legacy` option if you know the commands you want, then React never gets initialized and you never get the error.

Note that you *cannot* do `npx fauna-schema-migrate run --legacy` - the `run` option is unsupported.

**Comment by m4tty-d** [comment] 2021-11-08 18:28
Cool, thank you for looking into it! 🙏

**Comment by Shadid12** [comment] 2021-11-12 13:24
@m4tty-d here's the temporary workaround. This is happening because of conflicting react versions in the dependency tree.

```sh
npm install --save-dev @fauna-labs/fauna-schema-migrate
npm install --prefix ./node_modules/@fauna-labs/fauna-schema-migrate
```

**Comment by Shadid12** [comment] 2022-01-12 17:40
should be fixed with the new release [v.2.2.0](https://www.npmjs.com/package/@fauna-labs/fauna-schema-migrate)

**Closed by Shadid12** 2022-01-12 17:40 UTC
Labels: bug
